/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';

export type { AgencyModel } from './models/AgencyModel';
export type { B2BLoginModel } from './models/B2BLoginModel';
export { Code } from './models/Code';
export type { DepartmentModel } from './models/DepartmentModel';
export type { DistrictModel } from './models/DistrictModel';
export type { DivisionEmailModel } from './models/DivisionEmailModel';
export type { DivisionModel } from './models/DivisionModel';
export type { EmailTemplateModel } from './models/EmailTemplateModel';
export { EmailTemplateType } from './models/EmailTemplateType';
export type { ExamLocationModel } from './models/ExamLocationModel';
export type { ExamLocationRoomMapScheduleModel } from './models/ExamLocationRoomMapScheduleModel';
export type { ExamLocationRoomModel } from './models/ExamLocationRoomModel';
export type { ExamLocationScheduleModel } from './models/ExamLocationScheduleModel';
export type { ExamModel } from './models/ExamModel';
export type { ExamPaymentInformationModel } from './models/ExamPaymentInformationModel';
export type { ExamPaymentModel } from './models/ExamPaymentModel';
export type { ExamPublishedItemModel } from './models/ExamPublishedItemModel';
export type { ExamRegistrationProvinceModel } from './models/ExamRegistrationProvinceModel';
export type { ExamRegistrationScheduleModel } from './models/ExamRegistrationScheduleModel';
export type { ExamScheduleModel } from './models/ExamScheduleModel';
export { ExamScoreType } from './models/ExamScoreType';
export { ExamType } from './models/ExamType';
export { Gender } from './models/Gender';
export type { IIGDepartmentModel } from './models/IIGDepartmentModel';
export { InstitutionType } from './models/InstitutionType';
export type { LoginModel } from './models/LoginModel';
export type { NavigationModel } from './models/NavigationModel';
export { PaymentStatus } from './models/PaymentStatus';
export { PaymentType } from './models/PaymentType';
export type { PICModel } from './models/PICModel';
export { PICType } from './models/PICType';
export type { PolicyModel } from './models/PolicyModel';
export type { ProvinceModel } from './models/ProvinceModel';
export { ProvinceType } from './models/ProvinceType';
export type { PublishScheduleModel } from './models/PublishScheduleModel';
export type { PublishScoreModel } from './models/PublishScoreModel';
export { PublishType } from './models/PublishType';
export type { RegistrationCodeEmailModel } from './models/RegistrationCodeEmailModel';
export type { RegistrationCodeModel } from './models/RegistrationCodeModel';
export type { RegistrationCodeSyncModel } from './models/RegistrationCodeSyncModel';
export { RegistrationExamType } from './models/RegistrationExamType';
export type { RegistrationModel } from './models/RegistrationModel';
export type { RegistrationPaymentModel } from './models/RegistrationPaymentModel';
export { RegistrationRound } from './models/RegistrationRound';
export type { RegistrationScheduleEmailModel } from './models/RegistrationScheduleEmailModel';
export type { RegistrationScheduleEmailNotificationImportedModel } from './models/RegistrationScheduleEmailNotificationImportedModel';
export type { RegistrationScheduleModel } from './models/RegistrationScheduleModel';
export type { RegistrationScoreEmailModel } from './models/RegistrationScoreEmailModel';
export type { RegistrationScoreEmailNotificationImportedModel } from './models/RegistrationScoreEmailNotificationImportedModel';
export type { RegistrationScoreModel } from './models/RegistrationScoreModel';
export { RegistrationStatus } from './models/RegistrationStatus';
export type { ResponseData } from './models/ResponseData';
export type { RoleModel } from './models/RoleModel';
export type { SchoolEmailModel } from './models/SchoolEmailModel';
export { SchoolEmailType } from './models/SchoolEmailType';
export type { SchoolModel } from './models/SchoolModel';
export { SchoolType } from './models/SchoolType';
export type { ScoreReferenceModel } from './models/ScoreReferenceModel';
export type { SelectOptionModel } from './models/SelectOptionModel';
export { TemplateType } from './models/TemplateType';
export type { TransactionUpdateModel } from './models/TransactionUpdateModel';
export type { UserChangePassword } from './models/UserChangePassword';
export type { UserMetadataModel } from './models/UserMetadataModel';
export type { UserModel } from './models/UserModel';
export type { WardModel } from './models/WardModel';

export * as AgencyService from './services/AgencyService';
export * as AministrativeDivisionsService from './services/AministrativeDivisionsService';
export * as B2BAuthService from './services/B2BAuthService';
export * as DepartmentService from './services/DepartmentService';
export * as DivisionService from './services/DivisionService';
export * as EmailService from './services/EmailService';
export * as EmailTemplateService from './services/EmailTemplateService';
export * as ExamService from './services/ExamService';
export * as FileService from './services/FileService';
export * as IigDepartmentService from './services/IigDepartmentService';
export * as NavigationService from './services/NavigationService';
export * as PolicyService from './services/PolicyService';
export * as RegistrationService from './services/RegistrationService';
export * as RegistrationCodeService from './services/RegistrationCodeService';
export * as RegistrationPaymentService from './services/RegistrationPaymentService';
export * as RegistrationScheduleService from './services/RegistrationScheduleService';
export * as RegistrationScoreService from './services/RegistrationScoreService';
export * as ReportService from './services/ReportService';
export * as RoleService from './services/RoleService';
export * as SchoolService from './services/SchoolService';
export * as SchoolPermissionService from './services/SchoolPermissionService';
export * as ScoreReferenceService from './services/ScoreReferenceService';
export * as SystemSettingService from './services/SystemSettingService';
export * as TransactionService from './services/TransactionService';
export * as UserService from './services/UserService';
